--系统角色定义表
CREATE TABLE IDEA_TPL_ROLE(
	ID INT(15) NOT NULL AUTO_INCREMENT,
	ROLE_NAME VARCHAR(100),
	ROLE_DESC VARCHAR(200),
	AVAILABLE       CHAR(1),
	UPDATE_TIME     TIMESTAMP,
	UPDATE_BY       INT(15),
    CREATE_BY       INT(15),
    CREATE_TIME     TIMESTAMP,
	PRIMARY KEY(ID),
	UNIQUE(ROLE_NAME)
);
