--系统用户角色映射表
CREATE TABLE IDEA_USER_ROLE(
	ID INT(15) NOT NULL AUTO_INCREMENT,
	USER_ID         INT(15),
	ROLE_ID         INT(15),
	UPDATE_TIME     TIMESTAMP,
	UPDATE_BY       INT(15),
    CREATE_BY       INT(15),
    CREATE_TIME     TIMESTAMP,
	PRIMARY KEY(ID),
	UNIQUE(USER_ID,ROLE_ID)
);
